[package]
name = "sam4l"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]

[dependencies]
cortexm4 = { path = "../../arch/cortex-m4" }
crt0s = { path = "../../libraries/crt0s" }
kernel = { path = "../../kernel" }
